//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Croisieres
    {
        public Croisieres()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int IdCroisiere { get; set; }
        public int IdTheme { get; set; }
        public int IdDuree { get; set; }
        public Nullable<int> IdPromo { get; set; }
        public int IdPort { get; set; }
        public int Prix { get; set; }
        public System.DateTime DateDepart { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
    
        public virtual Durees Durees { get; set; }
        public virtual Ports Ports { get; set; }
        public virtual Promos Promos { get; set; }
        public virtual Themes Themes { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
