//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Durees
    {
        public Durees()
        {
            this.Croisieres = new HashSet<Croisieres>();
        }
    
        public int IdDuree { get; set; }
        public int NbJours { get; set; }
    
        public virtual ICollection<Croisieres> Croisieres { get; set; }
    }
}
