//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public string PhotoName { get; set; }
        public int IdCroisiere { get; set; }
        public System.Guid IdPhoto { get; set; }
    
        public virtual Croisieres Croisieres { get; set; }
    }
}
