//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int IdReservation { get; set; }
        public int IdCroisiere { get; set; }
        public string IdUtilisateur { get; set; }
        public int NbPlace { get; set; }
        public string MoyenPaiement { get; set; }
        public System.DateTime DateReservation { get; set; }
    
        public virtual Croisieres Croisieres { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
