//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int Id { get; set; }
        public System.DateTime DateInscription { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public string IdUtilisateur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> IdCroisiere { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Croisieres Croisieres { get; set; }
    }
}
